development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  database: tq_development
  pool: 5
  username: postgres
  password: postgres
test:
  adapter: postgresql
  encoding: unicode
  database: tq_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: tq_production
  pool: 5
  username: postgres
  password:
